version: 0.0
os: linux

files:
  - source: awspipelinedemo/target/awspipelinedemo.war
    destination: /home/ec2-user/tomcat/apache-tomcat-8.5.61/webapps/
  - source: awspipelinedemo/TestXMLFile.xml
    destination: /home/ec2-user/tomcat/apache-tomcat-8.5.61/webapps/
    
# hooks:
#   AfterInstall:
#     - location: server_start.sh
#       timeout: 300
#       runas: root
#   ApplicationStop:
#     - location: server_stop.sh
#       timeout: 300
#       runas: root 
